development:
  adapter: postgresql
  encoding: unicode
  database: malstrom
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: malstrom
  pool: 5
  username:
  password:
