# Do not keep production secrets in the repository,
# instead read values from the environment.
development:
  secret_key_base: "development-key"

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
